- src/Components/Home.js
- src/Components/MessageList.js
- src/Components/UserDetail.js
- src/Components/UserList.js
Adds a `MessageList` component to render Messages in a table on Home and User Profiles.
> MessageList

- src/Components/MessageList.js
Adds `topic` column in our Message List. The `Message.topic` is how we'll be able to determine how many Users entered each level of the Seatbelt Game (https://github.com/DoSomething/gambit-conversations/pull/88).
> Display Message.topic

- src/Components/ConversationDetail.js
- src/Components/ConversationList.js
- src/Components/MessageList.js
Makes changes per https://github.com/DoSomething/gambit-conversations/pull/91
> Conversations API changes

- src/App.css
- src/Components/ConversationList.js
- src/Components/MessageList.js
- src/config.js
* Sorts the Conversation list by `updatedAt`
* Tweaks the date for shorter width (now that we're displaying the Conversation ID), and adds a `config.dateFormat` to DRY
> Adds Conversation.updatedAt

- src/Components/MessageList.js
Refs https://github.com/DoSomething/gambit-conversations/pull/108
> Display Broadcast ID

- src/App.css
- src/Components/MessageList.js
> Render attachments

- src/Components/MessageList.js
Refs https://github.com/DoSomething/gambit-conversations/pull/119
> Display Message.agentId

- src/Components/ConversationDetail.js
- src/Components/ConversationList.js
- src/Components/Home.js
- src/Components/MessageList.js
- src/config.js
* Adds Next and Previous buttons to paginate through results of a GET messages query.
* Moves `message.template` into the details of a Message instead of a separate table column
> MessageList Pager

- package.json
- src/Components/ConversationList.js
- src/Components/Header.js
- src/Components/Home.js
- yarn.lock
Adds a Search form to the Navbar to find a Conversation by `platformUserId`.
> Search form

- src/App.css
- src/Components/CampaignDetail.js
- src/Components/CampaignList.js
- src/Components/ConversationDetail.js
- src/Components/ConversationList.js
- src/Components/GambitRequest.js
- src/Components/Header.js
- src/Components/Home.js
- src/Components/MessageList.js
Makes our `MessageList` component easier to read by using a `Grid` instead of a `Table`. Also removes Bootstrap fluid layout.
> Grid facelift

- src/Components/ConversationDetail.js
- src/Components/MessageList.js
Displays Conversation, Message topic
> Display topic

- client/src/Components/RequestError.js
- config/lib/middleware/authenticate.js
- lib/gambit-campaigns.js
- lib/gambit-conversations.js
- lib/helpers.js
- lib/middleware/authenticate.js
- package.json
- routes/index.js
- server.js
Closes #3, following [Gambit Conversations](https://github.com/DoSomething/gambit-conversations/blob/0.6.0/lib/middleware/authenticate.js) by example.
> Adds basic-auth middleware

- .env.example
- client/src/Components/ConversationDetail.js
- lib/helpers.js
- routes/gambit-conversations.js
Will add config vars to staging/prod and deploy this branch to confirm expected behavior.
> Link to User Profile in Aurora, Rogue, Mobile Commons

- .eslintignore
- .eslintrc.js
- client/.eslintrc.js
- client/package.json
- client/src/App.js
- client/src/App.test.js
- client/src/Components/CampaignDetail.js
- lib/gambit-campaigns.js
- lib/gambit-conversations.js
- lib/middleware/authenticate.js
- package.json
- routes/gambit-conversations.js
* Adds `eslintrc.js` for both server and client apps.
* Lints server code
* Starts on linting client code
> Lint server

- client/.eslintignore
- client/package.json
- client/src/Components/Broadcast/Broadcast.js
Updates `stats` per https://github.com/DoSomething/gambit-conversations/pull/252/, displaying:
* Total Outbound
* Total Inbound
* Total Yes
* Total No
* Total Unsubscribes
> Display Broadcast stats

- client/src/Components/ConversationDetail.js
Displays Northstar User info (and `addr_source` if it exists).
Refs https://github.com/DoSomething/gambit-conversations/pull/263
> Adds User Address info

- client/src/Components/ConversationDetail.js
- lib/northstar.js
- routes/gambit-conversations.js
Makes changes per https://github.com/DoSomething/gambit-conversations/pull/288 to load the Northstar User for a [Gambit Slack](https://github.com/dosomething/gambit-slack) conversation, making it easier to verify a User's subscription updates (status, paused).
> Fetch User for Slack Conversation

- client/src/Components/CampaignDetail.js
- client/src/Components/MessageList/MessageListContainer.js
Reads templates from the `response.botConfig.templates` instead of a `response.botConfig` per https://github.com/DoSomething/gambit-campaigns/pull/1033
> Gambit Campaigns API changes

- client/src/Components/ContentfulLink.js
- client/src/Components/Header.js
- client/src/Components/HttpRequest.js
- client/src/Components/Main.js
- client/src/Components/MessageList/MessageListContainer.js
- client/src/Components/MessageList/MessageListItem.js
- client/src/Components/TopicDetail/TopicDetailContainer.js
- client/src/Components/TopicList/TopicListContainer.js
- client/src/Components/TopicList/TopicListItem.js
- client/src/Components/TriggerList/TriggerListContainer.js
- client/src/Components/TriggerList/TriggerListItem.js
- client/src/helpers.js
- lib/gambit-campaigns.js
- routes/api.js
Adds a `TriggerList` components to view all `defaultTopicTriggers`, grouped by whether they changet the user's topic.
> View all triggers [pr]

- client/src/Components/BroadcastDetail/BroadcastDetail.js
- client/src/Components/BroadcastList/BroadcastListItem.js
Fixes broadcast views per https://github.com/DoSomething/gambit-conversations/pull/368, also fixes console errors found when viewing the `BroadcastDetail`.
> Check for broadcast.message.text

- .env.example
- config/lib/gambit-campaigns.js
- lib/gambit-campaigns.js
Includes a `x-gambit-api-key` header in Gambit Campaigns requests per https://github.com/DoSomething/gambit-campaigns/pull/1064
> Adds Gambit Campaigns API key

- client/src/Components/BroadcastDetail/BroadcastDetail.js
- client/src/Components/BroadcastList/BroadcastListContainer.js
- client/src/Components/BroadcastList/BroadcastListItem.js
- client/src/Components/TopicDetail/TopicDetail.js
- client/src/Components/TopicList/TopicListContainer.js
- client/src/Components/TopicList/TopicListItem.js
- client/src/helpers.js
This branch was used in tandem with the changes made to our topic and broadcast types in [gambit-campaigns](https://github.com/DoSomething/gambit-campaigns/tree/master/documentation). It feels a little gross to be using the dangerous HTML but it was easiest approach at the time of development.
> Adds broadcast and topic descriptions

- lib/gambit-campaigns.js
- lib/gambit-conversations.js
- package-lock.json
- package.json
- routes/api.js
- server.js
Proxies request to [`GET /contentfulEntries`](https://github.com/DoSomething/gambit-campaigns/blob/master/documentation/endpoints/contentfulEntries.md#retrieve-contentful-entries), to be used in https://github.com/DoSomething/gambit-slack/pull/41
> Adds proxy to get contentfulEntries, post messages

- client/src/Components/BroadcastDetail/BroadcastDetail.js
[Per Slack request.](https://dosomething.slack.com/archives/C2C8NLNAY/p1538417670000100)
> Calculate broadcast macro rate by outbound instead of replies

- client/src/Components/UserDetail/UserDetail.js
- client/src/Components/UserDetail/VotingPlan.js
Displays `voting_plan` fields on a User detail.
> Voting plan

- client/src/Components/TemplateList/TemplateListItem.js
- client/src/Components/UserDetail/VotingPlan.js
> Fixes non-voting status on votingPlan

- client/src/Components/SignupList/SignupListContainer.js
- client/src/Components/SignupList/SignupListItem.js
- client/src/Components/SignupList/SignupPost.js
- client/src/Components/UserDetail/UserDetail.js
* Removes signup list view into new `SignupList` components.
* Only renders a signup post media and quantity properties when they exist, making it easier to view text posts
Note: Using `object` for a prop type for now -- outstanding cleanup task to fix this in all components
> SignupList component [pr]

- client/src/Components/BroadcastDetail/BroadcastDetail.js
- client/src/Components/CampaignList/CampaignListContainer.js
- client/src/Components/CampaignList/WebSignupList.js
- client/src/Components/CampaignList/WebSignupListItem.js
- client/src/Components/ContentfulLink.js
- client/src/Components/Main.js
- client/src/Components/TopicDetail/TopicDetail.js
- client/src/helpers.js
Lists the campaigns that send SMS confirmations for web signups, per https://github.com/DoSomething/gambit-conversations/pull/423
> Web signups list [pr]

- client/src/Components/SignupList/SignupListContainer.js
- client/src/Components/SignupList/SignupListItem.js
- client/src/Components/SignupList/SignupPost.js
Frontend for https://github.com/DoSomething/gambit-conversations/pull/435
> Display source.details

- .env.example
- client/src/Components/GraphQLQuery.js
- client/src/Components/HttpRequest.js
- client/src/Components/ListForm.js
- client/src/Components/ListPager.js
- client/src/Components/PostList/PostListContainer.js
- client/src/Components/SignupList/SignupListContainer.js
- client/src/Components/SignupList/SignupListItem.js
- client/src/Components/SignupList/SignupPost.js
- client/src/Components/UserDetail/UserDetailContainer.js
- client/src/Components/UserDetail/UserSignups.js
- client/src/graphql.js
- client/src/helpers.js
This PR implements a few changes per #90 and #92 reviews, and completes feature parity with current production release.
* Adds signup permalink per https://github.com/DoSomething/graphql/pull/28
* Adds next and previous links for Signup and Post index views
* Defines GraphQL queries as constants per https://github.com/DoSomething/gambit-admin/pull/90/files#r245330991
* Adds GraphQL fragments per https://github.com/DoSomething/gambit-admin/pull/90#discussion_r245330273
* Updates OAuth client scopes per https://github.com/DoSomething/gambit-admin/pull/92/files#r245334902
> GraphQL cleanup

- .env.example
- client/src/Components/BroadcastDetail/BroadcastDetail.js
- client/src/Components/BroadcastList/BroadcastListItem.js
- client/src/Components/ContentfulLink.js
- config/services.js
- lib/contentful.js
- lib/gambit-conversations.js
- package-lock.json
- package.json
- routes/api.js
Opened in tandem with https://github.com/DoSomething/gambit-conversations/pull/465 - This PR causes the BroadcastDetail component from breaking, and queries Contentful directly for paginated lists of broadcasts... in anticipating of deprecating the Gambit Content `GET /broadcasts` resource.
> Hotfix BroadcastDetail [pr]

- client/src/Components/TopicDetail/TopicTemplates.js
- client/src/graphql.js
- config/services.js
Frontend changes per https://github.com/DoSomething/gambit/pull/473 and https://github.com/DoSomething/graphql/pull/54 and https://github.com/DoSomething/gambit/pull/476
> Renders AskVotingPlanStatusBroadcastTopic and AskMultipleChoiceBroadcastTopic templates

- client/src/Components/CampaignDetail/CampaignDetailContainer.js
- client/src/Components/CampaignList/ActiveCampaignList.js
- client/src/Components/CampaignList/ClosedCampaignList.js
- client/src/Components/WebSignupConfirmation.js
- client/src/graphql.js
- client/src/helpers.js
- Updates the `getCampaignDetailById` GraphQL query w/ new contract.
- Updates components that display campaign, keyword, and webConfirmations info.
- https://gambit-admin-staging.herokuapp.com/campaigns
- https://gambit-admin-staging.herokuapp.com/campaigns-ended
- https://gambit-admin-staging.herokuapp.com/campaigns/5646
> Update graphql query schemas (getCampaignDetailById)

- client/src/Components/TopicDetail/TopicDetailContainer.js
- client/src/graphql.js
- It updates the `getTopicById` GraphQL query.
- Fixes the `AskYesNo` topic detail view
> Update GraphQl query schemas (getTopicById)

- client/package-lock.json
- client/package.json
- client/src/Components/ConversationSearchForm.js
- client/src/Components/HttpRequest.js
- package-lock.json
This PR upgrades React to v16 and updates the `ConversationSearchForm` component to use State Hooks. This doesn't change any user-facing features, just was a good way to get in some professional development time.
> [pr] Refactor search form, HttpRequest with React Hooks
