DoSomething/gambit-admin

src/Components/Header.js
We're planning to use Aurora instead of a separate Gambit Admin web app, so it seems overkill to create different environments while we're in pre-production
In the meantime -- let's add a config variable to avoid hardcoding the site name in the navbar.
=> Site name override

src/Components/ConversationDetail.js, src/Components/ConversationList.js, src/Components/GambitRequest.js, src/Components/Home.js, src/Components/Main.js, src/Components/MessageList.js, src/config.js
* Adds a `GambitRequest` component to view MessageList by request ID:`/requests/:requestId` 
* Adds a `limit` filter to hotfix https://github.com/DoSomething/gambit-conversations/issues/163 and get Gambit Admin Staging running again
* Populates `conversationId` to display Platform User ID instead of Conversation ID
* Displays `retryCount` when exists
=> Gambit Request view

src/App.css, src/Components/CampaignDetail.js, src/Components/CampaignList.js, src/Components/Header.js, src/Components/Home.js, src/Components/Main.js, src/Components/MessageList.js
Picks up after #16 (needs #16 reviewed first)
Adds two new paths:
- `/campaigns`: Index of all active Gambit Campaigns
- `/campaigns/:id`: Campaign Detail that displays cached templates, filters messages by campaign
TODO: Add index to `Messages.campaignId` in Conversations API
=> Campaign List, Detail

.env.example, README.md, client/src/Components/CampaignDetail.js, client/src/Components/ConversationDetail.js, config/lib/northstar.js, lib/helpers.js, lib/northstar.js, package.json, routes/gambit-conversations.js
* Adds the Northstar JS package to fetch a User for SMS Conversations, and display relevant fields to Gambit (User ID, Paused, SMS Status, Last Messaged At).
* Renders detail info for Campaigns and Conversations with `Panel` and `Row` instead of `FormGroup`.
* Fixes bug in `helpers.sendResponseForError`
=> Display Northstar User on Conversation Detail 

client/package.json, client/src/Components/CampaignDetail.js, client/src/Components/CampaignTemplate.js, client/src/Components/MessageList.js
* Makes the Templates tab the default view of a Campaign Detail (`/campaigns/:id`)
* Adds [`react-scrollable-anchor`](https://www.npmjs.com/package/react-scrollable-anchor) and a `CampaignTemplate` component to link to a specific template row, e.g. http://gambit-admin-staging.herokuapp.com/campaigns/6620#invalidAskSignupResponse
=> Campaign Template permalinks

.env.example, client/package.json, client/src/Components/ConversationDetail.js, config/lib/rogue.js, lib/helpers.js, lib/rogue.js, routes/gambit-conversations.js
Branching from #28:
* This PR adds a Signups tab to the `ConversationDetail` component, querying the Rogue API to display the last 20 signups for the Conversation User. This helps make it easier for Gambit devs to test their code (did the Signup work?), and admins investigate support questions.
* Fixes `ConversationDetail` lint errors.
I'll be adding the config variables to staging and deploy this branch to confirm works as expected, and also edit this PR base to `master` once #28 is merged.
=> User Signups

client/src/Components/Broadcast/Broadcast.js, client/src/Components/Broadcast/BroadcastContainer.js, client/src/Components/BroadcastList.js, client/src/Components/Header.js, client/src/Components/Main.js, client/src/Components/MessageList.js, client/src/helpers.js, lib/gambit-conversations.js, routes/gambit-conversations.js
Starts on displaying data from the new [Conversations Broadcasts endpoint](https://github.com/DoSomething/gambit-conversations/pull/244).
* Adds a `/broadcasts` list view of all Conversations Broadcasts
* Adds a `/broadcasts/:id` view of a Broadcast, displaying total of inbound and outbound messages for the Broadcast, as well as the values to [use in the Customer.io setup](https://github.com/DoSomething/gambit-conversations/wiki/Broadcasts#2-get-broadcast-settings).
Will deploy to staging to confirm works as expected (https://github.com/DoSomething/gambit-conversations/pull/244 has been deployed to Conversations Staging).
=> Broadcasts

client/package.json, client/src/Components/Broadcast/Broadcast.js, client/src/Components/Broadcast/BroadcastContainer.js, client/src/Components/Broadcast/BroadcastReplyList.js, client/src/Components/Main.js, client/src/Components/MessageList/MessageList.js, client/src/Components/MessageList/MessageListContainer.js, client/src/Components/MessageList/MessageListItem.js
Adds lists of inbound messages replying to a Broadcast, grouped by Yes, No, Unsubscribe, and Other a la indices added in https://github.com/DoSomething/gambit-conversations/pull/258.
* Calls `MessageList` with a  new `table` prop. When set, renders the list as a Bootstrap Table.
Will deploy this branch to confirm 👍 and link to examples.
=> Broadcast replies

.env.example, client/src/Components/ConversationDetail.js, lib/helpers.js, routes/gambit-conversations.js
Removes the Links section on the Profile:
* Removes deprecated Mobile Commons URL
* Removes Rogue User URL - this data is displayed on the Signups tab in #29 
Note - the User ID field still links out to the User Aurora profile.
=> Removes Mobile Commons URL

client/src/Components/Broadcast/Broadcast.js
Rivescript topic broadcasts are showing invalid Other counts because the `confirmedCampaign` and `declinedCampaign` stats will never be set -- the Conversation topic is set to the Rivescript topic, where yes and no messages won't trigger the `confirmedCampaign` and `declinedCampaign` macros as they do in the `'campaign'` Rivescript topic.
This PR hides the Yes/No stats for Topic broadcasts and fixes the number of Other messages (in this case, only other than Stop macros).
=> Hide Yes/No stats for Topic broadcasts

client/src/Components/ConversationDetail.js, client/src/Components/ConversationList.js, client/src/Components/Header.js, client/src/Components/MessageList/MessageListItem.js, client/src/helpers.js, routes/gambit-conversations.js
Fetches User by `Conversation.userId` property if it exists, defaulting to fetch by mobile on the `platformUserId` otherwise. I'm working on adding a `userId` property to a Gambit Conversation and using this branch to test that things are working are expected (for new Conversations with a `userId`, and existing ones that don't have it yet)
* Also supports short-lived storing the User ID as `platformUserId` for Gambit Slack conversations over the past sprint or so.
* Displays the Northstar User ID instead of mobile number in the Conversation Detail `PageHeader`, renames the Conversations tab to Users to better indicate the PageHeader is the uid
TODO:
* Refactor `ConversationDetail` at `/conversation/:conversationId` to `UserDetail` at `/users/:userId`. All production users will only have …
=> Check for Conversation.userId

client/src/Components/ConversationSearchForm.js
Changed the `/conversations` URL to `/users` in #44 but forgot to update the search form redirect.
=> Fixes URL bug from #44

client/package-lock.json, client/package.json, client/src/Components/MessageList/MessageListItem.js, client/src/helpers.js, package-lock.json
Adds helper to list hardcoded Rivescript topics that shouldn't link to a `TopicDetail` view, as our Content API topics should. Also fixes #40
=> Adds helpers.getHardcodedTopics

client/src/Components/Broadcast/Broadcast.js
Instead of limiting broadcast reply stats to the `confirmedCampaign`, `declinedCampaign`, and `subscriptionStatusStop` macros, display stats for all macros triggered by replies, making it easier to view live stats for `askSubcriptionStatus` broadcasts. 
Note: this `Broadcast` component could use quite a bit of cleanup (cleanup props by defining a `broadcast` shape instead of object, rename to `BroadcastDetail` for consistency with other components, and splitting it out into functional components - e.g. `BroadcastDetailResponseStats`). Opening as-is to have stats in place for this week's `askSubscriptionStatus` broadcast.
=> Display broadcast stats for all macros

client/package-lock.json, client/package.json, client/src/Components/Broadcast/Broadcast.js, client/src/Components/CampaignDetail.js, client/src/Components/CampaignList.js, client/src/Components/ContentfulLink.js, client/src/Components/TopicDetail/TopicDetail.js, client/src/Components/TopicDetail/TopicTemplate.js, client/src/Components/TopicList/TopicListContainer.js, client/src/Components/TopicList/TopicListItem.js, client/src/Components/UserDetail/UserDetail.js, client/src/helpers.js
Frontend updates in tandem with https://github.com/DoSomething/gambit-campaigns/pull/1055
* Displays new topic name field
* Renders a topic list on a `CampaignDetail` instead of `TopicTemplate` components, linking to the various topics a campaign can have, removes tabs as the Campaign messages view didn't exactly work (query times out, and I don't think anyone's ever noticed or navigated to it)
* Updates React Bootstrap, and `Panel` components
* Adds a ` ContentfulLink` component to topic, broadcast detail views
Cleanup tasks for a separate PR:
* Split `CampaignDetail` and `CampaignList` components into separate container and content components like other components (e.g. `TopicDetail/TopicDetail.js, TopicDetail/TopicDetailContainer.js`
* Rename `Broadcast` component as `BroadcastDetail`
=> Display topic names + campaign topic list [pr]

client/src/Components/CampaignDetail.js, client/src/Components/CampaignList.js
Now that our changeTopicMacro triggers are published having deployed https://github.com/DoSomething/gambit-campaigns/pull/1055/, I've made the following Contentful changes:
- archived all `keyword` entries
- updated the keyword field's help text in Contentful to indicate we should no longer be creating keyword entries, as we're no longer querying for them 
TBD on removing the content type from Contentful completely (could make sense to run an[export](https://www.contentful.com/developers/docs/tutorials/general/import-and-export/), or just rely on the Staff Pick google doc the campaigns team uses)
=> Removes campaign keywords

client/src/Components/Main.js, client/src/Components/UserList/UserListContainer.js, client/src/Components/UserList/UserListItem.js
Even though this component queries the Gambit `/conversations` index endpoint, it links to `UserDetail` views, and is presented under the `Users` parent view -- so it felt cleaner to rename as `UserList`.
=> Renames ConversationList as UserList

.env.example, client/src/Components/BroadcastDetail/BroadcastDetail.js, client/src/Components/BroadcastList/BroadcastListItem.js, lib/gambit-conversations.js
* Adds support to query Conversations API v1 and v2 per https://github.com/DoSomething/gambit-conversations/pull/371
* NOTE: Requires changing `DS_GAMBIT_CONVERSATIONS_API_BASEURI` to remove `v1` after deploy. Because this app is not user facing, we can get away with changing the variable immediately after deploy.
* Cleanup TODOs from #62
=> Fixes breaking broadcasts API changes

.env.example, client/src/Components/BroadcastList/BroadcastListContainer.js, client/src/Components/HttpRequest.js, config/lib/gambit-conversations.js, lib/gambit-conversations.js
Updates the Conversations proxy response to return a `meta` object instead of `pagination` per https://github.com/DoSomething/gambit-campaigns/pull/1061.
Still need to add limit query parameter support in G-Campaigns to the `GET /broadcasts` index endpoint, opening this to test against that change (currently returns 100, but Gambit Admin has hardcoded limits of 50 for now -- which is why the results are incorrect on page 2 of broadcasts. Likewise could modify this app to have different page sizes per components, but doesn't seem worth the lift at the moment)
=> Adds broadcast pager

client/src/Components/BroadcastDetail/BroadcastDetail.js, client/src/Components/BroadcastDetail/BroadcastDetailContainer.js, client/src/Components/ContentfulLink.js, client/src/Components/TemplateList/TemplateList.js, client/src/Components/TemplateList/TemplateListItem.js, client/src/Components/TopicDetail/TopicDetail.js, client/src/Components/TopicDetail/TopicDetailContainer.js, client/src/Components/TopicDetail/TopicTemplate.js, client/src/Components/TopicDetail/TopicTemplates.js, client/src/Components/TriggerList/TriggerListItem.js, lib/gambit-campaigns.js, lib/gambit-conversations.js, routes/api.js
Front-end updates for https://github.com/DoSomething/gambit-campaigns/pull/1064
* Adds a cache clear button to allow manually flushing the redis cache for a broadcast or topic
* Renders templates for a broadcast if they exist.
* Refactors the `TopicDetail/TopicTemplate` component as`TemplateList` and `TemplateListItem`
=> Adds cache clear button, broadcast templates [pr]

client/src/Components/TriggerList/TriggerListContainer.js, client/src/Components/TriggerList/TriggerListItem.js, client/src/helpers.js, lib/gambit-conversations.js, routes/api.js
Refactors the TriggerList to query the Conversations rivescript endpoint, and trigger a Rivescript cache clear via query string.
NOTE: While testing this, I discovered a bug in Conversation where a Rivescript cache clear doesn't wipe the bot's loaded replies first, instead it adds to the number of replies to sort. Fix to be added in Conversations
Other notes:
* Includes all Rivescript, so hardcoded triggers for compliance, subscription status, and/or crisis messaging are visible
* Removes the topic title and campaign info from the reply list for now, as we're no longer sourcing the list from a `GET /defaultTopicTriggers` request. A future PR can add a query this endpoint to add the info (or ideally, hit up some GraphQL to avoid re-inventing the wheel)
=> Clear Rivescript cache [pr]

client/src/Components/TopicDetail/TopicDetail.js, client/src/helpers.js
Fixes errors per breaking changes in https://github.com/DoSomething/gambit-campaigns/pull/1094.
The way we'll render this list is by executing a `GET /defaultTopicTriggers` to find any keywords associated with the topic - but will add this in a future PR to keep things readable. Future PR will fix up the "keywords" section in the `CampaignList` component to render list of keywords (we'll also want to make these changes in Gambit Slack as well)
=> Removes list of triggers on TopicDetail

client/src/Components/BroadcastDetail/BroadcastDetail.js, client/src/Components/BroadcastDetail/BroadcastWebhook.js, client/src/Components/TopicDetail/TopicDetail.js, client/src/Components/TopicDetail/TopicDetailContainer.js
Viewing a topic broadcasts like an `askVotingPlanStatus` breaks when viewing as a `TopicDetail`, which can happen by clicking on the topic link within a `MessageList` -- This is a hotfix by returning the `BroadcastDetail` component instead of `TopicDetail` component when viewing the broadcast at `/topics/:id`.
Ideally our`MessageList` needs to know more info about each topic, so it can return the topic title instead of the id, and also link the to `/broadcasts/:id` instead of `/topics/:id` to access the stats and webhook settings.
=> Hotfix viewing a topic broadcast from /topics/:id

client/src/Components/AdminDashboard/AdminDashboard.js, client/src/Components/Header.js, client/src/Components/Main.js
#80 refactors the `TriggerList` component to query the `defaultTopicTriggers` endpoint, which is great because we get nested information about topics and campaigns. But it breaks the existing functionality on the `/triggers` page that was used to query the `rivescript` endpoint, and clear the Rivescript cache. This restores clearing Rivescript cache with old code from #80 in a WIP `AdminDashboard` component.
=> Restore clearing Rivescript cache

client/.eslintrc.js, client/src/Components/CampaignDashboard/CampaignDashboard.js, client/src/Components/CampaignDetail/CampaignDetail.js, client/src/Components/CampaignLink.js, client/src/Components/DraftSubmissionList/DraftSubmissionListContainer.js, client/src/Components/ListForm.js, client/src/Components/ListPager.js, client/src/Components/PostList/PostListContainer.js, client/src/Components/SignupList/SignupListContainer.js, client/src/Components/SignupList/SignupListItem.js, client/src/Components/SignupList/SignupPost.js, client/src/Components/UserDetail/UserDetail.js, client/src/helpers.js
Adds support to pass a `source` query parameter to filter signups or posts by source, e.g:
* https://gambit-admin.herokuapp.com/signups?source=sms
Adds support to pass a `type` query parameter by type, e.g:
* https://gambit-admin.herokuapp.com/signups?source=sms&type=text
Also adds helper for building the query string per https://github.com/DoSomething/gambit-admin/pull/85#discussion_r239550508.
Future PR hopes to add a form with select elements to add the query parameters.
=> Filter activity by source, type

client/src/Components/SignupList/SignupListItem.js, client/src/graphql.js
Follow up to https://github.com/DoSomething/graphql/pull/31, this PR displays "Invalid campaign" message if a campaign is not found for a given signup's `campaignId` property. Refs [bug reported in Slack](https://dosomething.slack.com/archives/C0YGXUE01/p1547004263042700).
=> Adds check for signup.campaign

client/src/App.js, client/src/Components/TemplateList/TemplateList.js, client/src/Components/TemplateList/TemplateListItem.js, client/src/Components/TopicDetail/TopicDetail.js, client/src/Components/TopicDetail/TopicDetailContainer.js, client/src/graphql.js, lib/graphql.js, routes/auth.js, server.js
Front-end updates per https://github.com/DoSomething/gambit-conversations/pull/461: 
* Fetches Topic detail from GraphQL
* Fetches GraphQL schema for Broadcast and Topic interfaces on app start, and exposes it in a `GET /auth/session` response, exposing to the client for InMemoryCache with IntrospectionFragmentMatcher
Note the cache clear button won't work anymore... ideally we'd like Contentful webhooks to clear the GraphQL and Gambit cache for an entry.
=> Fetch topic from GraphQL [pr]

client/src/Components/BroadcastDetail/BroadcastDetail.js, client/src/Components/BroadcastDetail/BroadcastDetailContainer.js, client/src/Components/BroadcastDetail/BroadcastStats.js, client/src/Components/BroadcastDetail/BroadcastStatsContainer.js, client/src/Components/TemplateList/TemplateList.js, client/src/Components/TopicDetail/TopicDetail.js, client/src/Components/TopicDetail/TopicTemplates.js, client/src/graphql.js
Front end changes for https://github.com/DoSomething/gambit/pull/471, with a bit of cleanup:
* Fetches a broadcast and its topic templates from GraphQL, instead of the Gambit `GET /broadcasts/:id` endpoint. Once this is in place, we'll refactor the Gambit `GET /broadcasts/:id` endpoint to only return broadcast stats (it's currently returning a similar GraphQL request for a `broadcast(id) -- but without the necessary topic templates to get the full view of all associated data)
* Splits the `BroadcastDetail` component out into `BroadcastStats` components
=> Fetch broadcast from GraphQL [pr]

client/src/Components/TemplateList/TemplateList.js, client/src/Components/TopicDetail/TopicTemplates.js, client/src/graphql.js
- It updates the `getBroadcastById` GraphQL query schema
- It updates the `TopicTemplates` and `TemplateList` components to use the new topic schema
- Make sure broadcast detail links are functional and render correctly. [Example](http://localhost:3001/broadcasts/5W9tjhwhDEbQekbpJTy0Ud)(AskYesNo)
- A `TemplateListItem` component that get a topic should render a link to the topic. Example seen in the link above.
=> Updates graphql query schemas (getBroadcastById)

client/src/Components/HttpRequest.js
#107 was making API requests continuously (hence #32), and unexpectedly.  I didn't catch this when I was working on local and staging, but for sure saw this in action on production when we sent out a broadcast. This PR passes an empty array as a second argument to the Effect Hook to avoid continuously making http requests after the component renders.
#107 also introduced a number of warning in the browser console. I may clean those up when there's time but for now, it seems wise to merge this and avoid regular polling.
=> [pr] Avoid polling requests in HttpRequest component

client/src/Components/HttpRequest.js
Fixes bug introduced in #107. The second page of Gambit API results (e.g. https://gambit-admin-staging.herokuapp.com/broadcasts?skip=50&) would throw an TypeError: `Cannot read property 'skipCount' of undefined`.
I'll deploy this branch to our staging Gambit Admin to confirm fix.
=> Fixes pagination for broadcasts

src/Components/AdminDashboard/AdminDashboard.js
This PR adds a link to a default topic trigger's Contentful ID if it exists, per https://github.com/DoSomething/gambit/pull/539
This `/triggers` view only displays triggers and their replies within the `random` topic. It could potentially useful for admins to see the triggers and replies in the hardcoded `unsubscribed`, `dss_`, or for users, or [voting plan](https://github.com/DoSomething/gambit/tree/main/brain/topics/votingPlan) RiveScript topics per Anthony's comment in https://www.pivotaltracker.com/n/projects/2401401/stories/174231934 (not being able to see all hardcoded triggers).
Here are ideas for displaying any other hardcoded triggers beyond the `random` topic ones:
* In a new section to bottom of the page in the `/triggers` view - seems easiest
* Add a check to`/topics/:id` to …
=> Adds link to Contentful ID on Triggers view

src/Components/BroadcastDetail/BroadcastStatsContainer.js, src/Components/BroadcastDetail/BroadcastWebhook.js
This fixes an issue where Customer.io would get mad when `customer.addr_state` was null. We had to swap this into Gambit Admin as a string template because this uses Liquid tags that wouldn't work well in the JSON payload we used to retrieve from Gambit's `v2/broadcasts` endpoint.
=> Update Customer.io payload to support null states.
